### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by OmniModz** [CameronRedmore/memory-deck#10]
Just an idea, would it ever be possible in the future for you to create a DLL injection plugin? The ability to quickly inject DLL's into running processes via the quick menu would be incredible. Great work by the way!

**Comment by HeyItsWaters** [comment]
@74892730 That'd be an interesting idea for a completely separate plugin.

I, myself, don't have any interest in creating that plugin today, just because I'm still struggling to understand how the memory-deck plugin/decky infrastructure works - however you might want to head over to the Steam Deck Homebrew discord and see if anybody is working on such a thing.


I'm closing this issue since it's not really relevant to the memory-deck plugin as it stands today.
