### ISSUE TITLE
Allow listing found addresses when results list is larger than 10.

### ISSUE THREAD

**Issue by eyeonus** [CameronRedmore/memory-deck#27]
It is not possible to find the health bar in Narita Boy (GOG), because any search returns 11 results. No matter how many times the health goes up or down, the number of matches never goes below 11.

This is true no matter what parameters are used in the search, or what "Search Type" is set to.

**Comment by HeyItsWaters** [comment]
@eyeonus The reason the limit is 10 is because of the limited room there is in the side menu. 

Are you recommending that we increase it to something else? Add another button to "Show All" if there's more than 10? What if there's 9001?

If you run the `main.py` file manually via SSH while playing the game, are you able to manipulate your health as you expect?
(Running the plugin manually like this will show you up to 50 results)

**Comment by eyeonus** [comment]
I figured it was something like that.

I suppose it depends on how rarely this particular issue occurs. If it is regularly the case that a search refuses to narrow down to 10 or less, then upping the limit to, say, 15, might be the best idea,

If this is something very rare, then a show all button (maybe that switches into browser mode, which has more space?) would be a better idea.

I'm only one person and have not used this plugin very much, so I have no idea what the problem frequency is.

I have not tried running via SSH and have no idea how to, but I do know that when I did the same search on my Win box using Cheat Engine, it also would not return less than 11 results, and result 11 was the one that was the actual health address, the other 10 results being of the "where on the health bar do we place this visual effect" variety.

**Comment by HeyItsWaters** [comment]
Since this is the only time I've heard of someone wanting to show more than 10 results I think we should chalk this up to an edgecase/outlier and not change the whole plugin.

If more folks want to "show all" or change the default to something else, we can collate the requests and make an update.

Until then I'm closing this for now. If you want to show more than 10 results (say 15 or 20), you can do so by 
A.) modifying the plugin and deploying it manually - Lines 415 and 416 of /src/index.tsx
or
B.) enabling SSH on your SteamDeck, and while your game is running, SSH into it and run `python /home/deck/homebrew/plugins/memory-deck/main.py`

Option B runs the plugin in interactive mode on the command line and has more flexibility/can be modified using SSH to behave how you want. This is actually how I personally do testing.

**Comment by eyeonus** [comment]
I have encountered another game, "Vernal Edge", in which I cannot get the results to be 10 or less.
In this case, I can not get it to go below 16, whilst trying to find the address for the value of the bar which when full allows execution of the character's special ability.

So, going with option B, how do I do 'increased', 'no change', '!=', and so on? The help text doesn't provide this information.

**Comment by tydavis** [comment]
@HeyItsWaters another game with >10 references is `Watch_Dogs` -- tends to show 14+ references for Money and other values.
