### ISSUE TITLE
More legible process names

### ISSUE THREAD

**Issue by cescofry** [CameronRedmore/memory-deck#32]
During the process selection we are provided a list of processes, but the names are quite long and contain the entire path, which makes it illegible and look quite junky.

<img width="1728" alt="Screenshot 2023-04-27 at 10 52 52 AM" src="https://user-images.githubusercontent.com/205915/234983103-4a7cd9c0-f29a-41cb-8d0d-da45d1edacd6.png">

**Comment by cescofry** [comment]
I think playing with running `ps -u 1000 -o pid,command` for filtering blacklist and then matching the pid with the results of  `ps -u 1000 co pid,command` should do the trick. (argument c shows only the process name instead of the path).

I should be able to make it work if there is interest.

**Comment by HeyItsWaters** [comment]
yes cleaning up the process list i agree with. i really wanted to only list the names and not paths, but it gets weird because some folks are using SteamOS to launch non-Steam games so it's kind of random where they are installed. sometimes having the context of where the game is installed is useful...if you can come up with an elegant solution i look forward to it.

**Comment by HeyItsWaters** [comment]
this should be resolved/improved with PR #48 

once v0.1.9 is released this will be available.
